export const REGISTER_PROGRESSBAR = 'REGISTER_PROGRESSBAR';
export const SET_PROGRESSBAR_ALL_STEPS = 'SET_PROGRESSBAR_ALL_STEPS';
export const SET_PROGRESSBAR_CURRENT_STEP = 'SET_PROGRESSBAR_CURRENT_STEP';
export const PROGRESSBAR_NEXT_STEP = 'PROGRESSBAR_NEXT_STEP';
export const PROGRESSBAR_PREV_STEP = 'PROGRESSBAR_PREV_STEP';